const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat("hu-HU",{style:"currency",currency:"HUF",maximumFractionDigits:0}).format(n),clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n)),rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,pick=a=>a[Math.floor(Math.random()*a.length)];
const names={female:["Anna","Emma","Lili","Nóra","Luca","Hanna","Sára","Zsófia"],male:["Bence","Dávid","Máté","Levente","Ádám","Marcell","Balázs","Péter"],neutral:["Alex","Noa","Sam","Robin","Dani"]},surnames=["Kovács","Nagy","Tóth","Szabó","Horváth","Varga","Kiss","Molnár","Farkas","Németh"];
const jobs=[["Munkanélküli",0,0],["Pincér",220000,10],["Eladó",260000,10],["Irodai asszisztens",330000,25],["Szakmunkás",420000,25],["Programozó",750000,55],["Mérnök",820000,60],["Orvos",1250000,80],["Ügyvéd",1050000,70],["Tanár",520000,45],["Rendőr",560000,45],["Pilóta",1100000,70],["Művész",480000,45],["Tartalomkészítő",650000,50],["Cégvezető",1800000,85],["Vállalkozó",0,65]];
const achievements=[["first-year","🌱","Első év","Éld túl az első évfordulót."],["millionaire","💎","Milliomos","Érj el 1 000 000 Ft vagyont."],["rich","👑","Nagypályás","Érj el 100 000 000 Ft vagyont."],["degree","🎓","Diplomás","Szerezz egy diplomát."],["married","💍","Igent mondtam","Házasodj meg."],["parent","👶","Szülő","Legyen gyermeked."],["travel","✈️","Világjáró","Utazz legalább 5 alkalommal."],["crime","🕶️","Tiltott ösvény","Kövess el egy bűncselekményt."],["car","🚗","Garázs","Legyen autód."],["house","🏠","Otthon","Legyen saját ingatlanod."],["old","🧓","Tapasztalat","Érd el a 80 éves kort."],["social","📱","Vírusos","Érd el az 1 000 000 követőt."]];
let state=null,saveKey="megalife-save-v1";
function fresh(){const gender=$("gender").value,first=$("firstName").value.trim()||pick(names[gender]||names.neutral),last=$("lastName").value.trim()||pick(surnames);return{version:1,alive:true,first,last,gender,country:$("country").value,age:0,year:new Date().getFullYear(),money:rand(20000,80000),debt:0,bank:0,health:rand(70,95),happiness:rand(55,85),smarts:rand(35,80),looks:rand(35,85),discipline:rand(30,80),karma:50,job:jobs[0],education:"Általános iskola",degree:null,relationships:[],children:[],family:{parents:[{name:pick(names.male)+" "+pick(surnames),type:"Apa",alive:true},{name:pick(names.female)+" "+pick(surnames),type:"Anya",alive:true}],siblings:rand(0,2)},assets:[],crimes:[],social:{followers:0,posts:0},travelCount:0,events:[],achievements:[],stats:{years:0,earned:0,spent:0,days:0,actions:0,relationships:0,children:0,crimes:0,investProfit:0,deathCause:null},flags:{married:false,university:false},traits:[pick(["Ambiciózus","Kreatív","Nyugodt","Vakmerő","Empatikus","Versengő"]),pick(["Társasági","Introvertált","Szerencsés","Makacs","Optimista","Spórolós"])],jail:0,business:null,pet:null}}}
function save(){if(!state)return;localStorage.setItem(saveKey,JSON.stringify(state));toast("Játék mentve.")}
function load(){try{const x=JSON.parse(localStorage.getItem(saveKey));if(x&&x.alive!==undefined){state=x;return true}}catch(e){}return false}
function toast(t){const e=$("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function log(text,type="Élet"){state.events.unshift({age:state.age,year:state.year,text,type});state.events=state.events.slice(0,80)}
function wealth(){return state.money+state.bank-state.debt+state.assets.reduce((s,a)=>s+(a.value||0),0)}
function fmt(n){return money(Math.round(n))}
function normalize(){for(const k of["health","happiness","smarts","looks","discipline","karma"])state[k]=clamp(state[k]);state.money=Math.max(0,Math.round(state.money));state.bank=Math.max(0,Math.round(state.bank));state.debt=Math.max(0,Math.round(state.debt))}
function render(){if(!state){$("startScreen").classList.remove("hidden");$("gameScreen").classList.add("hidden");return}$("startScreen").classList.add("hidden");$("gameScreen").classList.remove("hidden");$("pName").textContent=state.first+" "+state.last;$("avatar").textContent=state.first[0].toUpperCase();$("pMeta").textContent=state.age+" éves • "+state.gender+" • "+state.country;$("ageText").textContent=state.age+" éves";$("yearText").textContent=" • "+state.year;$("wealth").textContent=fmt(wealth());renderStats();renderLife();renderRelations();renderCareer();renderFinance();renderAssets();renderActivities();renderAchievements();renderStatsTab()}
function renderStats(){const d=[["❤️ Egészség",state.health],["😊 Boldogság",state.happiness],["🧠 Intelligencia",state.smarts],["✨ Kinézet",state.looks],["🎯 Fegyelem",state.discipline]];$("statBars").innerHTML='<div class="stats">'+d.map(x=>'<div class="stat"><span>'+x[0]+'</span><div class="bar"><i style="width:'+x[1]+'%"></i></div><b>'+Math.round(x[1])+'</b></div>').join("")+"</div>"}
function panel(t,b){return'<div class="card panel"><h3>'+t+"</h3>"+b+"</div>"}
function renderLife(){const jail=state.jail>0?panel("⚖️ Jogi helyzet",`<div class="action"><b>Börtönben vagy</b><small>Még ${state.jail} év van hátra.</small></div>`):"";const traits=panel("Személyiséged",`<div class="row">${state.traits.map(t=>`<span class="pill">${t}</span>`).join("")}</div>`);const ev=state.events.slice(0,12).map(e=>`<div class="event"><span class="tag">${e.year} • ${e.type}</span>${e.text}</div>`).join("")||'<div class="muted">Még nincs történés. Nyomd meg a Következő év gombot!</div>';const f=`<div class="grid"><div class="action"><b>👨‍👩‍👧 Szülők</b><small>${state.family.parents.map(p=>p.name).join(" • ")}</small></div><div class="action"><b>👶 Gyerekek</b><small>${state.children.length} gyermek</small></div><div class="action"><b>👥 Testvérek</b><small>${state.family.siblings} testvér</small></div><div class="action"><b>💼 Munka</b><small>${state.job[0]}</small></div></div>`;$("tab-life").innerHTML=jail+traits+panel("Életút",f)+panel("Legutóbbi események",ev)}\nfunction renderRelations(){let r=state.relationships.map((x,i)=>'<div class="list-item"><div><b>'+x.name+'</b> <span class="pill">'+x.type+'</span><br><small class="muted">'+x.age+" éves • kapcsolat: "+x.closeness+"%</small></div><button class="ghost" onclick="interact("+i+')">Interakció</button></div>').join("");if(!r)r='<p class="muted">Még nincs közeli kapcsolatod.</p>';$("tab-relations").innerHTML=panel("Kapcsolataid",r)+panel("Család",'<div class="grid"><button class="action" onclick="dateAction()"><b>❤️ Randi</b><small>Ismerkedj új emberrel.</small></button><button class="action" onclick="proposal()"><b>💎 Eljegyzés</b><small>85%+ kapcsolat esetén.</small></button><button class="action" onclick="marryAction()"><b>💍 Házasság</b><small>Ha van megfelelő párod.</small></button><button class="action" onclick="childAction()"><b>👶 Gyermek</b><small>Gyermekvállalás.</small></button></div>')}
function renderCareer(){const business=state.business?panel("Vállalkozás",'<div class="grid"><div class="action"><b>🏢 '+state.business.name+'</b><small>Érték: '+fmt(state.business.value)+'</small></div><button class="action" onclick="sellBusiness()"><b>💼 Eladás</b><small>Értékesítsd a céged.</small></button></div>'):panel("Vállalkozás",'<button class="action" onclick="startBusiness()"><b>🚀 Vállalkozás indítása</b><small>1 000 000 Ft indulótőke.</small></button>');const current='<div class="grid"><div class="action"><b>'+state.job[0]+'</b><small>Éves fizetés: '+fmt(state.job[1])+'</small></div><div class="action"><b>'+state.education+'</b><small>'+(state.degree||"Nincs diploma")+"</small></div></div>";const j=jobs.filter(x=>x[0]!==state.job[0]).map(x=>'<button class="action" onclick="getJob('+jobs.indexOf(x)+')"><b>'+x[0]+'</b><small>'+fmt(x[1])+" / év • IQ "+x[2]+"+</small></button>").join("");$("tab-career").innerHTML=panel("Karrier",current)+panel("Álláskeresés",'<div class="grid">'+j+'</div>')+panel("Oktatás",'<div class="grid"><button class="action" onclick="study()"><b>📚 Tanulás</b><small>Intelligencia és fegyelem.</small></button><button class="action" onclick="university()"><b>🎓 Egyetem</b><small>Diploma és jobb állások.</small></button></div>')}
function renderFinance(){$("tab-finance").innerHTML=panel("Pénzügyek",'<div class="grid"><div class="action"><b>Készpénz</b><small>'+fmt(state.money)+'</small></div><div class="action"><b>Bank</b><small>'+fmt(state.bank)+'</small></div><div class="action"><b>Tartozás</b><small>'+fmt(state.debt)+'</small></div><div class="action"><b>Teljes vagyon</b><small>'+fmt(wealth())+'</small></div></div>')+panel("Műveletek",'<div class="grid"><button class="action" onclick="bank(50000)"><b>🏦 Betét</b><small>+50 000 Ft bankba</small></button><button class="action" onclick="bank(-50000)"><b>💳 Kivét</b><small>50 000 Ft kivétele</small></button><button class="action" onclick="loan()"><b>💸 Hitel</b><small>Vegyél fel hitelt.</small></button><button class="action" onclick="invest()"><b>📈 Befektetés</b><small>Kockázatos hozam.</small></button><button class="action" onclick="gamble()"><b>🎰 Szerencsejáték</b><small>Nyerhetsz vagy veszíthetsz.</small></button></div>')}
function renderAssets(){const a=state.assets.map((x,i)=>'<div class="list-item"><div><b>'+x.icon+" "+x.name+'</b><br><small class="muted">Érték: '+fmt(x.value)+'</small></div><button class="ghost" onclick="sellAsset('+i+')">Eladás</button></div>').join("")||'<p class="muted">Még nincs jelentős vagyontárgyad.</p>';$("tab-assets").innerHTML=panel("Vagyontárgyak",a)+panel("Vásárlás",'<div class="grid"><button class="action" onclick="buyHouse()"><b>🏠 Lakás</b><small>6 000 000 Ft</small></button><button class="action" onclick="buyCar()"><b>🚗 Autó</b><small>3 000 000 Ft</small></button><button class="action" onclick="buyLuxury()"><b>💎 Luxusóra</b><small>1 200 000 Ft</small></button></div>')}
function renderActivities(){$("tab-activities").innerHTML=panel("Mindennapok",'<div class="grid"><button class="action" onclick="activity(\'exercise\')"><b>🏋️ Edzés</b><small>Egészség +, boldogság +</small></button><button class="action" onclick="activity(\'meditate\')"><b>🧘 Meditáció</b><small>Stresszcsökkentés.</small></button><button class="action" onclick="activity(\'party\')"><b>🎉 Buli</b><small>Boldogság +, pénz −</small></button><button class="action" onclick="activity(\'doctor\')"><b>🏥 Orvos</b><small>Egészség javítása.</small></button><button class="action" onclick="activity(\'social\')"><b>📱 Közösségi média</b><small>Követők.</small></button><button class="action" onclick="travel()"><b>✈️ Utazás</b><small>250 000 Ft.</small></button><button class="action" onclick="crime()"><b>🕶️ Bűncselekmény</b><small>Nagy kockázat.</small></button><button class="action" onclick="pet()"><b>🐕 Háziállat</b><small>Új családtag.</small></button></div>')}
function renderAchievements(){$("tab-achievements").innerHTML=panel("Eredmények",achievements.map(a=>'<div class="achievement list-item"><div class="ico">'+a[1]+'</div><div style="flex:1"><b>'+a[2]+'</b><br><small class="muted">'+a[3]+'</small></div><span class="pill">'+(state.achievements.includes(a[0])?"✓":"—")+"</span></div>").join(""))}
function renderStatsTab(){$("tab-stats").innerHTML=panel("Életstatisztika",'<div class="grid">'+[["Megélt évek",state.stats.years],["Összes kereset",fmt(state.stats.earned)],["Összes költés",fmt(state.stats.spent)],["Kapcsolatok",state.stats.relationships],["Gyerekek",state.stats.children],["Bűncselekmények",state.stats.crimes],["Utazások",state.travelCount],["Befektetési profit",fmt(state.stats.investProfit)],["Követők",state.social.followers]].map(x=>'<div class="action"><b>'+x[0]+'</b><small>'+x[1]+"</small></div>").join("")+"</div>")+panel("Karma",'<div class="meter"><i style="width:'+state.karma+'%"></i></div><small class="muted">Karma: '+Math.round(state.karma)+'/100</small>')}
function start(){state=fresh();log("Megszülettél. A történeted most kezdődik.","Sors");save();render();toast("Új élet elindítva!")}
function nextYear(){if(!state||!state.alive)return;state.age++;state.year++;state.stats.years++;state.stats.days+=365;state.stats.actions++;state.relationships.forEach(r=>r.age++);state.children.forEach(ch=>ch.age++);if(state.jail>0){state.jail--;state.health=clamp(state.health-rand(1,4));state.happiness=clamp(state.happiness-rand(3,8));log("Börtönben töltöttél egy évet. Még "+state.jail+" év van hátra.","Jog")}if(state.business){const profit=Math.round(state.business.value*(Math.random()*.12-.03));state.business.value=Math.max(0,state.business.value+profit);state.money+=Math.max(0,profit);if(profit>0)state.stats.earned+=profit;log("A vállalkozásod éves eredménye: "+fmt(profit)+".","Üzlet")}state.assets.forEach(a=>{if(a.income){state.money+=a.income;state.stats.earned+=a.income}});if(state.age>=18&&state.jail===0){const income=state.job[1];state.money+=Math.round(income/12);state.stats.earned+=Math.round(income/12);if(state.job[0]!=="Munkanélküli")log("Megkaptad a havi fizetésed: "+fmt(Math.round(income/12)),"Pénz")}state.bank=Math.round(state.bank*1.025);const expense=state.age<18?rand(1000,6000):rand(60000,Math.max(70000,Math.round((state.job[1]||150000)/5)));if(state.money>=expense){state.money-=expense;state.stats.spent+=expense}else{state.debt+=expense-state.money;state.money=0;log("Nem tudtad fedezni a kiadásaidat, nőtt a tartozásod.","Pénz")}state.happiness-=rand(0,5);state.health-=state.age>60?rand(1,5):rand(0,2);if(state.age===6)log("Elkezdted az általános iskolát.","Oktatás");if(state.age===14)log("Középiskolás lettél.","Oktatás");if(state.age===18)log("Nagykorú lettél.","Mérföldkő");if(state.age===65)log("Nyugdíjas korba léptél.","Mérföldkő");randomLifeEvent();if(state.age>=18&&state.job[0]!=="Munkanélküli"&&Math.random()<.18){state.job=[state.job[0]+" • Előléptetve",Math.round(state.job[1]*1.18),state.job[2]];log("Előléptettek a munkahelyeden!","Karrier")}if(Math.random()<.18)choiceEvent();checkAchievements();if(state.age>70&&Math.random()<Math.min(.06,(state.age-70)*.006))die(pick(["időskori természetes okok","szívprobléma","betegség"]));normalize();save();render()}
function randomLifeEvent(){if(Math.random()>.62)return;pick([()=>{const n=rand(5000,80000);state.money+=n;log("Egy távoli rokon "+fmt(n)+" örökséget hagyott rád.","Szerencse")},()=>{state.happiness=clamp(state.happiness+rand(8,18));log("Fantasztikus napot töltöttél a barátaiddal.","Élet")},()=>{state.health=clamp(state.health-rand(8,20));log("Elkaptál egy kellemetlen betegséget.","Egészség")},()=>{const n=rand(10000,120000);state.money+=n;state.stats.earned+=n;log("Egy váratlan mellékesből "+fmt(n)+" érkezett.","Pénz")},()=>{if(state.job[0]!=="Munkanélküli"){state.job=[state.job[0]+" • Senior",Math.round(state.job[1]*1.25),state.job[2]];log("Előléptettek! A fizetésed 25%-kal nőtt.","Karrier")}},()=>{if(state.social.followers>100){const n=rand(1000,20000);state.social.followers+=n;log("Egy posztod felrobbant az interneten, +"+n+" követő.","Közösség")}},()=>{if(state.relationships.length){state.relationships[0].closeness=clamp(state.relationships[0].closeness+15);log(state.relationships[0].name+" meglepett egy ajándékkal.","Kapcsolat")}}])()}
function dateAction(){if(state.age<14)return toast("Még túl fiatal vagy a randizáshoz.");const r={name:pick(names.female.concat(names.male).concat(names.neutral))+" "+pick(surnames),age:state.age+rand(-2,3),type:"Randi",closeness:rand(40,75)};state.relationships.push(r);state.stats.relationships++;log("Megismerkedtél "+r.name+" nevű emberrel.","Kapcsolat");render()}
function interact(i){const r=state.relationships[i];r.closeness=clamp(r.closeness+rand(5,18));state.happiness=clamp(state.happiness+rand(2,7));log("Időt töltöttél "+r.name+" társaságában. Kapcsolat: "+r.closeness+"%.","Kapcsolat");render()}
function marryAction(){const r=state.relationships.find(x=>x.closeness>=70);if(!r)return toast("Nincs még elég erős kapcsolatod.");state.flags.married=true;r.type="Házastárs";state.happiness=clamp(state.happiness+15);log("Összeházasodtál "+r.name+"-nel!","Kapcsolat");checkAchievements();render()}
function childAction(){if(!state.flags.married)return toast("Előbb házasodj meg.");if(state.age<18||state.age>50)return toast("Ebben az életkorban ez most nem lehetséges.");const child={name:pick(names.female.concat(names.male))+" "+state.last,age:0};state.children.push(child);state.stats.children++;log("Megszületett "+child.name+"!","Család");checkAchievements();render()}
function study(){if(state.age<6)return toast("Még nem vagy iskolás.");state.smarts=clamp(state.smarts+rand(2,7));state.discipline=clamp(state.discipline+rand(1,5));log("Sokat tanultál, az intelligenciád nőtt.","Oktatás");render()}
function university(){if(state.age<17||state.age>35)return toast("Az egyetemhez megfelelő életkor kell.");if(state.smarts<45)return toast("Fejleszd az intelligenciád.");state.flags.university=true;state.education="Egyetem";state.degree=pick(["informatika","mérnöki","orvosi","jogi","gazdasági"]);state.smarts=clamp(state.smarts+rand(8,18));state.money-=Math.min(state.money,rand(100000,400000));log("Elvégezted az egyetemet: "+state.degree+" diploma.","Oktatás");checkAchievements();render()}
function getJob(i){const j=jobs[i];if(state.age<16)return toast("Még túl fiatal vagy ehhez.");if(state.smarts<j[2])return toast("Ehhez az álláshoz több intelligencia/tanulmány kell.");if(j[0]==="Orvos"&&!state.degree)return toast("Ehhez diploma kell.");state.job=j;log("Új munkád lett: "+j[0]+".","Karrier");render()}
function bank(amount){if(amount>0){if(state.money<amount)return toast("Nincs ennyi készpénzed.");state.money-=amount;state.bank+=amount}else{const n=Math.min(state.bank,-amount);state.bank-=n;state.money+=n}save();render()}
function loan(){const n=rand(500000,3000000);state.money+=n;state.debt+=Math.round(n*1.2);log("Felvettél "+fmt(n)+" hitelt.","Pénz");render()}
function invest(){if(state.money<100000)return toast("Legalább 100 000 Ft kell.");const stake=rand(100000,Math.min(2000000,state.money));state.money-=stake;const ret=Math.round(stake*(Math.random()*.9+.55));state.money+=ret;state.stats.investProfit+=ret-stake;log("Befektetés: "+fmt(stake)+" → "+fmt(ret)+".","Pénz");render()}
function gamble(){if(state.money<10000)return toast("Legalább 10 000 Ft kell.");const stake=rand(10000,Math.min(250000,state.money));state.money-=stake;if(Math.random()<.43){const win=stake*rand(2,5);state.money+=win;log("Nagyot nyertél: "+fmt(win)+"!","Szerencse")}else log("Elvesztetted a feltett "+fmt(stake)+" összeget.","Szerencse");render()}
function buy(name,icon,value){if(state.money<value)return toast("Nincs elég pénzed.");state.money-=value;state.assets.push({name,icon,value});state.stats.spent+=value;log("Megvásároltad: "+name+".","Vagyon");checkAchievements();render()}
function buyHouse(){buy("Belvárosi lakás","🏠",6000000)}function buyCar(){buy("Sportos autó","🚗",3000000)}function buyLuxury(){buy("Luxusóra","💎",1200000)}
function sellAsset(i){const a=state.assets[i],v=Math.round(a.value*rand(75,105)/100);state.money+=v;state.assets.splice(i,1);log("Eladtad: "+a.name+" "+fmt(v)+" összegért.","Vagyon");render()}
function activity(t){if(t==="exercise"){state.health=clamp(state.health+rand(5,12));state.happiness=clamp(state.happiness+3);log("Edzettél és jobban érzed magad.","Egészség")}if(t==="meditate"){state.happiness=clamp(state.happiness+rand(4,10));state.discipline=clamp(state.discipline+3);log("Meditáltál, kitisztult a fejed.","Élet")}if(t==="party"){const c=rand(5000,50000);state.money=Math.max(0,state.money-c);state.happiness=clamp(state.happiness+rand(8,16));log("Buliztál egy nagyot, "+fmt(c)+"-ba került.","Élet")}if(t==="doctor"){if(state.money<50000)return toast("Az orvosi vizit 50 000 Ft.");state.money-=50000;state.health=clamp(state.health+rand(10,25));log("Elmentél orvoshoz.","Egészség")}if(t==="social"){const gain=rand(50,3000)+Math.round(state.looks*8);state.social.followers+=gain;state.social.posts++;log("Új posztod "+gain+" új követőt hozott.","Közösség")}render();checkAchievements()}
function travel(){if(state.money<250000)return toast("Az utazás 250 000 Ft.");state.money-=250000;state.travelCount++;state.happiness=clamp(state.happiness+rand(10,20));log("Elutaztál egy új országba.","Utazás");checkAchievements();render()}
function pet(){if(state.assets.some(a=>a.name.includes("Háziállat")))return toast("Már van háziállatod.");buy("Háziállat","🐕",150000)}
function crime(){if(state.age<16)return toast("Még túl fiatal vagy.");if(state.jail>0)return toast("Börtönben vagy.");const gain=rand(100000,1500000);state.stats.crimes++;state.crimes.push({age:state.age});if(Math.random()<.32){const sentence=rand(1,6);state.jail+=sentence;state.debt+=rand(100000,800000);state.happiness-=15;log("Elkövettél egy bűncselekményt, elkaptak és "+sentence+" év börtönt kaptál.","Jog")}else{state.money+=gain;state.karma-=20;log("Sikeres bűncselekmény: "+fmt(gain)+" zsákmány.","Jog")}checkAchievements();render()}
function die(cause){state.alive=false;state.stats.deathCause=cause;log("Meghaltál "+state.age+". éves korodban. Ok: "+cause+".","Halál");save();render();showDeath()}
function showDeath(){$("modalBody").innerHTML='<div class="death"><h2>🪦 Az életed véget ért</h2><p>'+state.first+" "+state.last+" "+state.age+" évet élt.</p><p><b>Halál oka:</b> "+state.stats.deathCause+'</p><p class="muted">Vagyon: '+fmt(wealth())+" • Gyerekek: "+state.children.length+" • Utazások: "+state.travelCount+'</p><button class="primary big" onclick="closeModal();newLife()">Új élet</button></div>';$("modal").classList.remove("hidden")}
function checkAchievements(){const c={"first-year":state.age>=1,"millionaire":wealth()>=1000000,"rich":wealth()>=100000000,"degree":!!state.degree,"married":state.flags.married,"parent":state.children.length>0,"travel":state.travelCount>=5,"crime":state.crimes.length>0,"car":state.assets.some(a=>a.name.includes("autó")),"house":state.assets.some(a=>a.name.includes("lakás")),"old":state.age>=80,"social":state.social.followers>=1000000};for(const a of achievements)if(c[a[0]]&&!state.achievements.includes(a[0])){state.achievements.push(a[0]);log("🏆 Eredmény feloldva: "+a[2],"Eredmény");toast("🏆 "+a[2])}}
function newLife(){localStorage.removeItem(saveKey);state=null;$("modal").classList.add("hidden");render()}
function showTab(tab){document.querySelectorAll(".tab").forEach(e=>e.classList.add("hidden"));$("tab-"+tab).classList.remove("hidden");document.querySelectorAll("#tabs button").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab))}
function closeModal(){$("modal").classList.add("hidden")}
$("startBtn").onclick=start;$("ageBtn").onclick=()=>state&&state.alive?nextYear():showDeath();$("saveBtn").onclick=save;$("newBtn").onclick=()=>{if(confirm("Biztosan új életet kezdesz?"))newLife()};$("modalClose").onclick=closeModal;$("tabs").addEventListener("click",e=>{const b=e.target.closest("button[data-tab]");if(b)showTab(b.dataset.tab)});if(load()){render();$("saveNotice").textContent="Mentett játék betöltve."}else render();
function choiceEvent(){const events=[{title:"Kockázatos lehetőség",text:"Egy ismerősöd azt ajánlja, hogy fektess be egy új projektbe.",choices:[["💰 500 000 Ft befektetés",()=>{if(state.money<500000)return toast("Nincs elég pénzed.");state.money-=500000;const win=Math.random()<.58;const n=win?rand(700000,1800000):0;state.money+=n;log(win?"A projekt hatalmasat ment: +"+fmt(n)+".":"A projekt bedőlt, elvesztetted a pénzed.","Döntés") }],["❌ Nem vállalom",()=>log("Nem vállaltad a kockázatot.","Döntés")]]},{title:"Életfordító találkozás",text:"Egy régi ismerős újra felbukkan az életedben.",choices:[["❤️ Közeledj hozzá",()=>{dateAction();state.happiness=clamp(state.happiness+8)}],["👋 Maradj távol",()=>{state.karma=clamp(state.karma+2);log("Továbbmentél.","Döntés")}]]},{title:"Karrierdöntés",text:"Felajánlanak egy nehezebb, de jobban fizető pozíciót.",choices:[["🚀 Elfogadom",()=>{if(state.age<18)return toast("Ehhez nagykorúnak kell lenned.");state.job=["Projektvezető",Math.max(700000,state.job[1]*1.35),Math.max(55,state.job[2])];log("Elfogadtad az új pozíciót.","Karrier")}],["🧘 Maradok",()=>{state.happiness=clamp(state.happiness+4);log("A stabilitást választottad.","Döntés")}]]}];const e=pick(events);$("modalBody").innerHTML="<h2>"+e.title+"</h2><p>"+e.text+"</p>"+e.choices.map((x,i)=>'<button class="choice" onclick="resolveChoice('+i+')">'+x[0]+"</button>").join("");window.__choices=e.choices.map(x=>x[1]);$("modal").classList.remove("hidden")}
function resolveChoice(i){const fn=window.__choices&&window.__choices[i];closeModal();if(fn){fn();normalize();save();render()}}
function startBusiness(){if(state.age<18)return toast("Vállalkozást nagykorúként indíthatsz.");if(state.business)return toast("Már van vállalkozásod.");if(state.money<1000000)return toast("Legalább 1 000 000 Ft indulótőke kell.");state.money-=1000000;state.business={name:pick(["Nova Labs","Urban Works","Pixel Forge","Mega Market","Stellar Studio"]),value:1000000};log("Elindítottad a saját vállalkozásodat: "+state.business.name+".","Üzlet");render()}
function sellBusiness(){if(!state.business)return toast("Nincs vállalkozásod.");const v=Math.round(state.business.value*(.7+Math.random()*.7));state.money+=v;log("Eladtad a vállalkozásodat "+fmt(v)+" összegért.","Üzlet");state.business=null;render()}
function proposal(){const r=state.relationships.find(x=>x.closeness>=85);if(!r)return toast("Ehhez legalább 85%-os kapcsolat kell.");r.type="Jegyes";r.closeness=95;log("Eljegyezted "+r.name+"-t.","Kapcsolat");render()}
